### PR TITLE
fix(utils-split): dismiss inner observable on error

### PR DESCRIPTION
**Pull request by josepot**
ups!

### CODE REVIEW

**Review by rikoe — APPROVED** [review]
Is this use case covered by a test?

**Comment by josepot** [comment]
> Is this use case covered by a test?

Of course, our code-coverage is 100%! that means that everything is covered by tests, right?

Just kidding! I've been trying to write a test for this, but I'm having a very hard time coming up with a decent one, but you are right, I won't merge it until I can write that test. Just to be clear, the test should not pass on the current `main` branch and it should pass after these changes.

Thanks @rikoe !

**Comment by josepot** [comment]
@all-contributors please add @rikoe for review

**Review by voliva — APPROVED** [review]

**Review by rikoe — APPROVED** [review]

**Comment by josepot** [comment]
The first commit is a test that doesn't pass on main ([I made sure that the CI ran on that commit and that the test fails](https://github.com/re-rxjs/react-rxjs/runs/1095688098)) and the second commit is the one that fixes the issue.

**Pull request merged**
