### PR TITLE
feat(utils): partitionByKey && mergeActiveKeys

### PR DESCRIPTION
**Pull request by josepot**
Hopefully this will allow us to deprecate the following utils:
- `split`
- `collect`
- `collectValues`

While also providing a simpler way to create subscriptions for parametric bind Observables.

@voliva could you please finish this?

### CODE REVIEW

**Comment by josepot** [comment]
Code coverage went down to 99.53%... alt text

**Comment by josepot** [comment]
I know that we've had this conversation "offline" before, but I really think that the order of the return value of `partitionByKey` should be reversed: first the inner-observable-getter and then the observable of keys... :thinking: 
image

**Review by voliva — APPROVED** [review]
👍 

Combinekeys test has a typo: emmit vs emit

**Comment by josepot** [comment]
> Combinekeys test has a typo: emmit vs emit

Fixed! Thanks!

**Pull request merged**
